"""Rules builder - builds different parts of cursor rules."""
from typing import Optional
from datetime import datetime
from src.database.models import Project
from .project_analyzer import ProjectAnalyzer


class RulesBuilder:
    """Builds cursor rules content in modular sections."""
    
    @staticmethod
    def build_header(project: Project) -> str:
        """Build rules file header."""
        return f"""---
name: intracker-project-rules
description: Cursor AI instructions for {project.name}
version: {datetime.utcnow().isoformat()}
---

# Cursor Rules for {project.name}

{project.description or ''}
"""
    
    @staticmethod
    def build_project_info(project: Project) -> str:
        """Build project information section."""
        tags_str = ', '.join(project.tags) if project.tags else 'None'
        tech_tags_str = ', '.join(project.technology_tags) if project.technology_tags else 'None'
        github_str = project.github_repo_url or 'Not connected'
        
        return f"""## Project Information

- **Project ID:** {project.id}
- **Status:** {project.status}
- **Tags:** {tags_str}
- **Technology Tags:** {tech_tags_str}
- **GitHub:** {github_str}
"""
    
    @staticmethod
    def build_cursor_instructions(cursor_instructions: str) -> str:
        """Build cursor instructions section."""
        return f"""## Cursor Instructions

{cursor_instructions}
"""
    
    @staticmethod
    def build_environment_strategy() -> str:
        """Build environment strategy section."""
        return """## Development Rules

### Environment Strategy

- **MVP Phase:** All development in local Docker environment
- **Post-MVP:** Deploy to Azure (staging → production)
- **Never deploy to Azure during MVP development**

"""
    
    @staticmethod
    def build_project_specific_info(project: Project) -> str:
        """Build project-specific information section."""
        updated_at_str = project.updated_at.isoformat() if project.updated_at else 'Unknown'
        
        return f"""
### Project-Specific Information

**This section is dynamically generated for each project:**
- Project ID: {project.id}
- Current status: {project.status}
- Active features: Check resume context
- Next todos: Check resume context
- Blockers: Check resume context
- Constraints: Check resume context

**To get latest project state:**
- `mcp_get_resume_context(projectId)` - Full current state
- `mcp_get_project_context(projectId)` - Complete project info
- `mcp_get_active_todos(projectId)` - Current todos

---

**Generated by InTracker MCP Server**
**Last updated:** {updated_at_str}
**Project:** {project.name}
"""
    
    @staticmethod
    def get_placeholder_replacements(project: Project) -> dict:
        """Get dictionary of placeholder replacements for sections."""
        return {
            "{DOCKER_SERVICES}": ProjectAnalyzer.get_docker_services(project),
            "{FRONTEND_SERVICE}": ProjectAnalyzer.get_frontend_service_info(project),
            "{MCP_SERVICE}": ProjectAnalyzer.get_mcp_service_info(project),
            "{BACKEND_RESTART_INFO}": ProjectAnalyzer.get_backend_restart_info(project),
            "{FRONTEND_RESTART_INFO}": ProjectAnalyzer.get_frontend_restart_info(project),
            "{MCP_RESTART_INFO}": ProjectAnalyzer.get_mcp_restart_info(project),
            "{uses_mcp}": str(ProjectAnalyzer.uses_mcp(project)),
        }
