"""init

Revision ID: 8be276c52a41
Revises: 
Create Date: 2026-01-05 17:52:58.064937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be276c52a41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('technology_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_session_at', sa.DateTime(), nullable=True),
    sa.Column('resume_context', sa.JSON(), nullable=True),
    sa.Column('cursor_instructions', sa.Text(), nullable=True),
    sa.Column('github_repo_url', sa.String(), nullable=True),
    sa.Column('github_repo_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('github_username', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('total_todos', sa.Integer(), nullable=False),
    sa.Column('completed_todos', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_features_assigned', 'features', ['assigned_to'], unique=False)
    op.create_index('idx_features_project', 'features', ['project_id'], unique=False)
    op.create_index('idx_features_status', 'features', ['status'], unique=False)
    op.create_index(op.f('ix_features_assigned_to'), 'features', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_features_status'), 'features', ['status'], unique=False)
    op.create_table('github_sync',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('github_type', sa.String(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_direction', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'github_type', 'github_id')
    )
    op.create_index('idx_github_sync_entity', 'github_sync', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_github_sync_project', 'github_sync', ['project_id'], unique=False)
    op.create_table('ideas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('converted_to_project_id', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['converted_to_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideas_status'), 'ideas', ['status'], unique=False)
    op.create_table('project_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('definition_of_done', sa.Text(), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_issue_url', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['project_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_elements_parent', 'project_elements', ['parent_id'], unique=False)
    op.create_index('idx_project_elements_project', 'project_elements', ['project_id'], unique=False)
    op.create_index('idx_project_elements_status', 'project_elements', ['status'], unique=False)
    op.create_index(op.f('ix_project_elements_status'), 'project_elements', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('feature_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('todos_completed', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('features_completed', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('elements_updated', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_project', 'sessions', ['project_id'], unique=False)
    op.create_index('idx_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_started_at'), 'sessions', ['started_at'], unique=False)
    op.create_table('user_projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_index('idx_user_projects_project', 'user_projects', ['project_id'], unique=False)
    op.create_index('idx_user_projects_user', 'user_projects', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['project_elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_element', 'documents', ['element_id'], unique=False)
    op.create_index('idx_documents_project', 'documents', ['project_id'], unique=False)
    op.create_index('idx_documents_type', 'documents', ['type'], unique=False)
    op.create_index(op.f('ix_documents_type'), 'documents', ['type'], unique=False)
    op.create_table('element_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_element_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_element_id'], ['project_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['element_id'], ['project_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('element_id', 'depends_on_element_id')
    )
    op.create_index('idx_dependencies_depends_on', 'element_dependencies', ['depends_on_element_id'], unique=False)
    op.create_index('idx_dependencies_element', 'element_dependencies', ['element_id'], unique=False)
    op.create_table('feature_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['project_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id', 'element_id')
    )
    op.create_index('idx_feature_elements_element', 'feature_elements', ['element_id'], unique=False)
    op.create_index('idx_feature_elements_feature', 'feature_elements', ['feature_id'], unique=False)
    op.create_table('github_branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('base_branch', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ahead_count', sa.Integer(), nullable=False),
    sa.Column('behind_count', sa.Integer(), nullable=False),
    sa.Column('has_conflicts', sa.Boolean(), nullable=False),
    sa.Column('last_commit_sha', sa.String(), nullable=True),
    sa.Column('last_commit_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'branch_name')
    )
    op.create_index('idx_branches_feature', 'github_branches', ['feature_id'], unique=False)
    op.create_index('idx_branches_project', 'github_branches', ['project_id'], unique=False)
    op.create_index('idx_branches_status', 'github_branches', ['status'], unique=False)
    op.create_index(op.f('ix_github_branches_status'), 'github_branches', ['status'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('estimated_effort', sa.Integer(), nullable=True),
    sa.Column('blocker_reason', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_pr_number', sa.Integer(), nullable=True),
    sa.Column('github_pr_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['project_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_todos_assigned', 'todos', ['assigned_to'], unique=False)
    op.create_index('idx_todos_created_by', 'todos', ['created_by'], unique=False)
    op.create_index('idx_todos_element', 'todos', ['element_id'], unique=False)
    op.create_index('idx_todos_feature', 'todos', ['feature_id'], unique=False)
    op.create_index('idx_todos_status', 'todos', ['status'], unique=False)
    op.create_index(op.f('ix_todos_assigned_to'), 'todos', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_todos_created_by'), 'todos', ['created_by'], unique=False)
    op.create_index(op.f('ix_todos_status'), 'todos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_status'), table_name='todos')
    op.drop_index(op.f('ix_todos_created_by'), table_name='todos')
    op.drop_index(op.f('ix_todos_assigned_to'), table_name='todos')
    op.drop_index('idx_todos_status', table_name='todos')
    op.drop_index('idx_todos_feature', table_name='todos')
    op.drop_index('idx_todos_element', table_name='todos')
    op.drop_index('idx_todos_created_by', table_name='todos')
    op.drop_index('idx_todos_assigned', table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_github_branches_status'), table_name='github_branches')
    op.drop_index('idx_branches_status', table_name='github_branches')
    op.drop_index('idx_branches_project', table_name='github_branches')
    op.drop_index('idx_branches_feature', table_name='github_branches')
    op.drop_table('github_branches')
    op.drop_index('idx_feature_elements_feature', table_name='feature_elements')
    op.drop_index('idx_feature_elements_element', table_name='feature_elements')
    op.drop_table('feature_elements')
    op.drop_index('idx_dependencies_element', table_name='element_dependencies')
    op.drop_index('idx_dependencies_depends_on', table_name='element_dependencies')
    op.drop_table('element_dependencies')
    op.drop_index(op.f('ix_documents_type'), table_name='documents')
    op.drop_index('idx_documents_type', table_name='documents')
    op.drop_index('idx_documents_project', table_name='documents')
    op.drop_index('idx_documents_element', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_user_projects_user', table_name='user_projects')
    op.drop_index('idx_user_projects_project', table_name='user_projects')
    op.drop_table('user_projects')
    op.drop_index(op.f('ix_sessions_started_at'), table_name='sessions')
    op.drop_index('idx_sessions_user', table_name='sessions')
    op.drop_index('idx_sessions_project', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_project_elements_status'), table_name='project_elements')
    op.drop_index('idx_project_elements_status', table_name='project_elements')
    op.drop_index('idx_project_elements_project', table_name='project_elements')
    op.drop_index('idx_project_elements_parent', table_name='project_elements')
    op.drop_table('project_elements')
    op.drop_index(op.f('ix_ideas_status'), table_name='ideas')
    op.drop_table('ideas')
    op.drop_index('idx_github_sync_project', table_name='github_sync')
    op.drop_index('idx_github_sync_entity', table_name='github_sync')
    op.drop_table('github_sync')
    op.drop_index(op.f('ix_features_status'), table_name='features')
    op.drop_index(op.f('ix_features_assigned_to'), table_name='features')
    op.drop_index('idx_features_status', table_name='features')
    op.drop_index('idx_features_project', table_name='features')
    op.drop_index('idx_features_assigned', table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
