"""add_teams_invitation_codes_user_role

Revision ID: 9c2737554492
Revises: a2ba13b96d48
Create Date: 2026-01-08 08:22:06.004502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2737554492'
down_revision: Union[str, Sequence[str], None] = 'a2ba13b96d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_teams_created_by', 'teams', ['created_by'], unique=False)
    op.create_index(op.f('ix_teams_created_by'), 'teams', ['created_by'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('invitation_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invitation_codes_code', 'invitation_codes', ['code'], unique=False)
    op.create_index('idx_invitation_codes_created_by', 'invitation_codes', ['created_by'], unique=False)
    op.create_index('idx_invitation_codes_team', 'invitation_codes', ['team_id'], unique=False)
    op.create_index('idx_invitation_codes_type', 'invitation_codes', ['type'], unique=False)
    op.create_index(op.f('ix_invitation_codes_code'), 'invitation_codes', ['code'], unique=True)
    op.create_index(op.f('ix_invitation_codes_created_by'), 'invitation_codes', ['created_by'], unique=False)
    op.create_index(op.f('ix_invitation_codes_team_id'), 'invitation_codes', ['team_id'], unique=False)
    op.create_index(op.f('ix_invitation_codes_type'), 'invitation_codes', ['type'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id')
    )
    op.create_index('idx_team_members_team', 'team_members', ['team_id'], unique=False)
    op.create_index('idx_team_members_user', 'team_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    # Add role column as nullable first
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # Set default value for existing users
    op.execute("UPDATE users SET role = 'member' WHERE role IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'role', nullable=False, server_default='member')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index('idx_team_members_user', table_name='team_members')
    op.drop_index('idx_team_members_team', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_invitation_codes_type'), table_name='invitation_codes')
    op.drop_index(op.f('ix_invitation_codes_team_id'), table_name='invitation_codes')
    op.drop_index(op.f('ix_invitation_codes_created_by'), table_name='invitation_codes')
    op.drop_index(op.f('ix_invitation_codes_code'), table_name='invitation_codes')
    op.drop_index('idx_invitation_codes_type', table_name='invitation_codes')
    op.drop_index('idx_invitation_codes_team', table_name='invitation_codes')
    op.drop_index('idx_invitation_codes_created_by', table_name='invitation_codes')
    op.drop_index('idx_invitation_codes_code', table_name='invitation_codes')
    op.drop_table('invitation_codes')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_created_by'), table_name='teams')
    op.drop_index('idx_teams_created_by', table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
